# GitHub Pages configuration for Luno MCP Server
title: "Luno MCP Server"
description: "Model Context Protocol server for Luno cryptocurrency exchange"
baseurl: ""
url: "https://amanasmuei.github.io/luno-mcp"

# Theme
theme: minima

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include the donation page
include:
  - donate.html

# SEO and social
author: "Abdul Rahman M Asmuei"
