# GitHub Pages configuration for Luno MCP Server
title: "Luno MCP Server"
description: "Model Context Protocol server for Luno cryptocurrency exchange"
baseurl: "/mcp-luno"
url: "https://amanasmuei.github.io"

# Theme
remote_theme: "pages-themes/minima@v2.5.1"

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Include the donation page
include:
  - donate.html

# SEO and social
author: "Abdul Rahman M Asmuei"
